# TODO Start: [Student] URL
image: registry.spring25b.secoder.net/tool/deployer
# TODO End

stages:
  - build
  - deploy

build:
  stage: build
  script: 
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build
  only:
    - master

deploy:
  stage: deploy
  script:
    - export API_SERVER="https://deployer.spring25b.secoder.net/api"
    - export DEPLOY_TOKEN="4256acca81ab1b4d8f05d215d11b86e8"
    - deployer dyno replace $CI_PROJECT_NAME "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$REGISTRY_USER" "$REGISTRY_PWD"
  only:
    - master
